version: "3.8"

services:
  backend:
    build:
      context: ./backend_llm
      dockerfile: Dockerfile
    container_name: backend_llm_container
    ports:
      - "8000:8000"
    # environment:
    #   - ANY_ENV_VARS=values
    # volumes:
    #   - ./backend_llm/uploads:/app/uploads
    # Add more config if needed

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend_container
    ports:
      - "3000:3000"
    depends_on:
      - backend
    # environment:
    #   - REACT_APP_BACKEND_URL=http://localhost:8000
    # If needed, define environment variables
